name: consume

on:
  workflow_run:
    workflows: ["produce"]
    types:
      - completed
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    if: >
       github.event.workflow_run.event == 'schedule' ||
       !contains(' main master ', format(' {0} ', github.event.workflow_run.head_branch))
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Dump GitHub context
      run: echo '${{ toJson(github.event.workflow_run) }}'
    - name: wait
      run: |
        echo "Event: ${{ github.event.workflow_run.event }}"
        echo "Head branch: ${{ github.event.workflow_run.head_branch }}"
