name: consume

on:
  workflow_run:
    workflows: ["produce"]
    types:
      - completed
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.workflow_run.event == 'schedule' || startswith(github.event.workflow_run.head_branch, 'refs/tags/')
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - name: wait
      run: sleep 10
